--- #YAML:1.0
name:               Geography-NationalGrid-TW
version:            0.08
abstract:           Module to convert Taiwan Datum (TWD67/TM2, TWD97/TM2) to/from Latitude and Longitude
author:
    - Yen-Ming Lee <leeym@leeym.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Geography::NationalGrid:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
